//
//  yeet_nifty_generated_c.c
//
//  Generated by the Nifty compiler v 0.0.1 on 10/18/2023.
//  !!! All changes made to this file will be overwritten. !!!
//

#include <inttypes.h>
#ifndef __cplusplus
#	include <stdbool.h>
#endif

typedef uint8_t nifty_u8;
typedef uint16_t nifty_u16;
typedef uint32_t nifty_u32;
typedef uint32_t nifty_uint;
typedef uint64_t nifty_u64;
typedef int8_t nifty_s8;
typedef int16_t nifty_s16;
typedef int32_t nifty_s32;
typedef int64_t nifty_s64;
typedef float nifty_f32;
typedef double nifty_f64;
typedef char* nifty_cstring;
typedef void* nifty_rawptr;
typedef uint32_t nifty_char;
typedef uint8_t nifty_b8;
typedef uint16_t nifty_b16;
typedef uint32_t nifty_b32;
typedef uint64_t nifty_b64;

int __nifty_start();

int __nifty_start() {
    return 2 + 2;
}

#include <stdio.h>

int main(void) {
	printf("Calling __nifty_start()...\n");
	return __nifty_start();
}
